# Generated by Django 2.2.10 on 2020-03-24 01:35

from django.db import migrations, models
import server.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200302_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='payload',
            field=models.FileField(blank=True, upload_to=server.apps.files.models.gen_filename),
        ),
    ]
