# Generated by Django 2.2.10 on 2020-03-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_auto_20200302_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('files', models.ManyToManyField(blank=True, related_name='classes', to='files.File')),
            ],
        ),
    ]
