# Generated by Django 2.2.10 on 2020-03-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(default='-', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
