# Generated by Django 2.2.10 on 2020-03-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200302_0345'),
        ('course', '0003_course_unapproved_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rejected_files',
            field=models.ManyToManyField(blank=True, related_name='classes_reject', to='files.File'),
        ),
    ]
